### ISSUE TITLE
Improve dev process

### ISSUE THREAD

**Issue by dariocravero** [UXtemple/panels#7]
We need hot-reloading and such. It's not exactly there with browserify yet but it will be.

I'm currently using the following commands.

To run the server:

```
# from panels repo
./.bin/run-server uxtemple.com usepanels.com
```

*Apps have to be `npm link`ed*

To compile an app:

```
# from the app
./.bin/pacpan-watch
```

**TODO:**
- [ ] allowing dev right from the app's directory without having to clone panels,
- [x] client-side hot-reloading,
- [x] server hot-reloading.

**Comment by dariocravero** [comment]
Done but in a different way. We're sort of away from the server side of things for now although it's ready to be plugged in. [See this for ref](https://github.com/UXtemple/usepages/blob/master/package.json#L13).
